name: HugoBuildAndDeploy

on:
  workflow_dispatch:

  push:
    branches: [main]

jobs:
  HugoBuild:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      #TODO build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: apk
          path: ./${{ env.NAME }}/build/app/outputs/flutter-apk/app-release.apk

  DeployToGithubPages:
    needs: BuildWeb

    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
